### ISSUE TITLE
今天突然出现的问题=。=

### ISSUE THREAD

**Issue by jh0072110** [sjlleo/ehco.sh#13]
![image](https://user-images.githubusercontent.com/50496854/133958487-dff67e27-a7ad-448c-a70c-f8dce60276aa.png)
原本合适的转发出问题了，就重置了一下系统，看起来问题依旧emmm……

**Comment by sjlleo** [comment]
这种情况下一般是配置文件损坏了，可以把 `/usr/local/ehco/ehco.json ` 发送到 `i@leo.moe`，给我看一下吗？记得脱敏。

**Comment by jh0072110** [comment]
> 这种情况下一般是配置文件损坏了，可以把 `/usr/local/ehco/ehco.json ` 发送到 `i@leo.moe`，给我看一下吗？记得脱敏。

晚上发给您吧，反正试了好几次都有这个问题…脱敏这事倒是无所谓了…也不发在公共区域……

**Comment by jh0072110** [comment]
就特么尴尬…真要log的时候不出问题了……我先close了等出问题了再update吧……
