### ISSUE TITLE
配置文件放在哪儿的？

### ISSUE THREAD

**Issue by 110560** [sjlleo/ehco.sh#2]
想把当前转发机上配置文件拖到另外一台机器，直接读取配置文件使用，应该不用新机器上再手动一个一个加吧？

**Comment by sjlleo** [comment]
`ehco`的配置文件路径为`/usr/local/ehco/ehco.conf`
不需要手动添加。只需要在新机器首先安装`ehco`（执行选项1，在要求添加中转时`Control+C`终止脚本），然后再用旧机器上的`ehco.conf`配置文件直接覆盖后重启ehco即可。
如果您有任何问题欢迎继续提问哦。

**Comment by 110560** [comment]
好的 配置文件路径 写在教材 或者脚本里就好了

**Comment by sjlleo** [comment]
在脚本里有写哦，请您查阅`ehco.sh`中的
```bash
21行 ehco_conf_dir="/usr/local/ehco/"
91行 }" > $ehco_conf_dir/ehco.json
```
这是方便一些用户自定义配置文件的位置，故写成了2段拼接而成。
