### ISSUE TITLE
脚本可以增强下么？

### ISSUE THREAD

**Issue by 6FH74pVQWiv9eQ92uH** [sjlleo/ehco.sh#3]
现在添加多个中转的时候，每添加一个需要重新执行一次脚本，可以连续添加么？就是 添加完一个隧道后可以选择继续添加还是退出。

**Comment by sjlleo** [comment]
根据目前使用者的反馈来看，这种需求还是比较少的，但我会考虑在明天添加这个功能（目前只在中转模式添加，一般来说落地也只需要一个隧道到后端就够了吧）。
如果您有更好的想法也可以继续回复我QAQ

**Comment by 6FH74pVQWiv9eQ92uH** [comment]
是的呢，只有中转模式需要，落地不需要的。现在的gost，brook等其他一键脚本都有这个功能，确实会方便很多，大多数人的中转也不会就中转一个端口。谢谢作者的付出。

**Comment by 6FH74pVQWiv9eQ92uH** [comment]
> 如果您有更好的想法也可以继续回复我QAQ

对了，请问转发支持动态域名么？

**Comment by sjlleo** [comment]
**Code Review:**
a1686f5 - ✔支持了「连续添加」的功能，部分细节做了优化调整
\---------------------------------------------------------------------
ehco是支持动态域名的转发的，而且也支持IPv6的转发，性能要略好于gost，断流的概率更低。

**Comment by 6FH74pVQWiv9eQ92uH** [comment]
> **Code Review:**
> [a1686f5](https://github.com/sjlleo/ehco.sh/commit/a1686f5d3a9e84d1e2fbc3dd038ef2d8dbadaaad) - ✔支持了「连续添加」的功能，部分细节做了优化调整
> ---------------------------------------------------------------------
> ehco是支持动态域名的转发的，而且也支持IPv6的转发，性能要略好于gost，断流的概率更低。

辛苦！效率很高！

**Comment by sjlleo** [comment]
如果您喜欢本脚本的话不要忘记Star支持我一下哦，谢谢啦~

**Comment by sjlleo** [comment]
如果没有其他问题，我将关闭此Issue。

**Comment by 6FH74pVQWiv9eQ92uH** [comment]
> 如果没有其他问题，我将关闭此Issue。

可以关闭，已star，谢谢
