### ISSUE TITLE
在arm主机上显示的错误咋办。。。

### ISSUE THREAD

**Issue by 110560** [sjlleo/ehco.sh#6]
Ehco状态： 正在运行

请输入选项：7
check python3-dbus......ok
check requests......no
[Info]  开始安装requests包
Traceback (most recent call last):
  File "/usr/local/ehco/configurev01.py", line 3, in <module>
    import requests
ImportError: No module named 'requests'

import dbus
import json
import requests
'''
-----------------------------------------
Version: 0.1
Author: sjlleo
Description: Ehco Configure Manage Script
-----------------------------------------
'''
def ShowAllRelayConfigs(json_data):
    print("当前有"+str(len(json_data['relay_configs']))+"条中转")

**Comment by sjlleo** [comment]
这个脚本依赖于`requests`包，您的`GNU/Linux`系统有`Python3`吗？您的`Python3`包组件是由`pip3`管理吗？如果是的话，请您执行`pip3 install requests`来手动安装`requests`包。

**Comment by sjlleo** [comment]
如果没有其他问题，我将关闭此Issue。
