### ISSUE TITLE
好像有点小bug

### ISSUE THREAD

**Issue by jh0072110** [sjlleo/ehco.sh#7]
转发同一个服务器的不同端口貌似会产生启动失败的情况…

**Comment by sjlleo** [comment]
![image](https://user-images.githubusercontent.com/13616352/129564996-373c0cba-af7f-41b2-9479-2c783deac12d.png)
您好，我根据您所说的尝试复现这个问题，但是看起来一切都正常，请您运行命令`cat /usr/local/ehco/ehco.json`将输出贴在下方，敏感信息可以用xx来表示，谢谢！

**Comment by jh0072110** [comment]
额，没有复现…我之前用的中文版说明文档里的国内链接（后来用了github里的），是不是那个脚本没更新的缘故（我看链接地址不同）？

**Comment by sjlleo** [comment]
> 额，没有复现…我之前用的中文版说明文档里的国内链接（后来用了github里的），是不是那个脚本没更新的缘故（我看链接地址不同）？

中文版说明的脚本更新频率要低于GitHub，建议优先使用GitHub的脚本源。
