### ISSUE TITLE
Ehco状态未在运行

### ISSUE THREAD

**Issue by cckkrr** [sjlleo/ehco.sh#8]
落地机添加完落地模式后显示正在运行，可是退出脚本再次进入之后又显示未在运行了，请问这是怎么回事呢？

**Comment by sjlleo** [comment]
终端执行命令`cat /usr/local/ehco/ehco.conf`，把输出贴到这里来，记得脱敏。

**Comment by cckkrr** [comment]
原来是我的落地运行着gost，我把gost停止，再把ehco运行就可以了，不过没想明白为啥会这样。

**Comment by sjlleo** [comment]
> 原来是我的落地运行着gost，我把gost停止，再把ehco运行就可以了，不过没想明白为啥会这样。

如果gost和ehco监听端口相同，会导致相互冲突，使得ehco直接停止运行。

**Comment by cckkrr** [comment]
监听端口和代理端口都不冲突，这就是我还没搞明白的，理论上应该互不影响才对？

**Comment by sjlleo** [comment]
> 监听端口和代理端口都不冲突，这就是我还没搞明白的，理论上应该互不影响才对？

ehco启动后会自动监听9000端口作为自己的管理端口，看看是不是和gost在这个端口上冲突了。

**Comment by cckkrr** [comment]
原来如此，是我忽略了原作者的文档。真的是太巧了，我原来gost就有一个监听端口是9000，这样就说得通啦。感谢大佬解惑！

**Comment by sjlleo** [comment]
没关系呀，ehco的监听端口是可以更改的，相关设置在在配置文件`/usr/local/ehco/ehco.conf`里面，修改后重启ehco就自动应用了。如果喜欢这个脚本的话可以给我一个Star鼓励一下哦~ 感谢您的使用！
